name: "build-and-check"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 13.x
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: Install
        run: yarn install --no-progress --non-interactive --skip-integrity-check
      - name: Build
        run: yarn build
      - name: Check
        run: yarn ci
      - name: Run end-to-end tests
        uses: cypress-io/github-action@v2
        with:
          # todo: create another job and use jobs[id].strategy to parallelize
          # I'm not doing this now, because transfering artifacts between
          # jobs is a bother.
          # record: true
          # parallel: true
          start: yarn start
          working-directory: packages/app
        env:
          CYPRESS_AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          CYPRESS_AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          CYPRESS_AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          CYPRESS_TEST_ACCOUNT_UNVERIFIED:
            ${{ secrets.TEST_ACCOUNT_UNVERIFIED }}
          CYPRESS_TEST_ACCOUNT_DEFAULT: ${{ secrets.TEST_ACCOUNT_DEFAULT }}

    env:
      CI: true
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
      AUTH0_COOKIE_SECRET: ${{ secrets.AUTH0_COOKIE_SECRET }}
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      HASURA_ADMIN_SECRET: ${{ secrets.HASURA_ADMIN_SECRET }}
      NEXT_PUBLIC_HASURA_URL: ${{ secrets.NEXT_PUBLIC_HASURA_URL }}
      NEXT_PUBLIC_ZAGRAJMY_REST_API_URL:
        ${{ secrets.NEXT_PUBLIC_ZAGRAJMY_REST_API_URL }}
